source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

workspace 'MLLayoutDemo.xcworkspace'

target 'MLLayoutDemo' do
	project 'MLLayoutDemo.xcodeproj'
	pod 'SDWebImage'
	pod 'MLLayout', :path => '../MLLayout.podspec'
end
